### PR TITLE
Replace terminal launch of nodes with systemd; tweak rewards formatting

### PR DESCRIPTION
**Pull request by davepuchyr**
It was late when I created this PR.  I've done the setup procedure several times and it woks for me, but it'd be good to have one of you successfully launch a node with it.  Please give it a try and scrutinize my work.

### CODE REVIEW

**Comment by ruseinov** [comment]
According to your script the directory should be in `DIR_WORK`. But I guess you have already fixed this.

I'm curious why are you asking about `too many open files`, did you have this issue before? AFAIK this setup shouldn't be a root cause of such an issue.

**Comment by ruseinov** [comment]
I must also say that I wouldn't use docker as preferred runtime environment, as there are some nuances with disk i/o and volume mounts, not to mention that Docker is usually hosted in a VM unless you are using linux.

Some good reading about volume mounts and their implications here: https://docs.docker.com/docker-for-mac/osxfs-caching/ .

**Comment by davepuchyr** [comment]
> According to your script the directory should be in `DIR_WORK`. But I guess you have already fixed this.
> 
> I'm curious why are you asking about `too many open files`, did you have this issue before? AFAIK this setup shouldn't be a root cause of such an issue.

Good morning!  I commingled two issues in my previous comment.  That was confusing.  Sorry.

Re too many open files, I've seen a lot of Cosmos operators that don't use docker have the problem.  I have LimitNOFILE=4096 my the unit file for cosmos, don't run gaiad in docker, and don't have the problem, so I wonder if a ulimit in the BNS docker container is require.

**Comment by davepuchyr** [comment]
> I must also say that I wouldn't use docker as preferred runtime environment, as there are some nuances with disk i/o and volume mounts, not to mention that Docker is usually hosted in a VM unless you are using linux.

What is your recommended setup?  I'm certainly not married to docker. :)

> 
> Some good reading about volume mounts and their implications here: https://docs.docker.com/docker-for-mac/osxfs-caching/ .

**Comment by ruseinov** [comment]
You can set a ulimit with modern docker like this: https://stackoverflow.com/a/31474407

I would recommend running a go binary for optimal performance for both tendermint and bns.

**Comment by ruseinov** [comment]
Although we can still use dockerized tools for app init and such.

I'll let @alpe chip in on this too.

**Comment by alpe** [comment]
I have not used systemd for quite some time but without running it it looked 🙆‍♂ . I am not sure what is left in this PR to do so I just comment on some security concerns regarding the docker setup:

- Run Image[@ digest] instead of tag on production. A tag can be moved
- `--user=uid:gid` Always run with non root (default) user
- `--read-only`		Mount the container’s root filesystem as read only
- Limit resources (cpu/ ram) https://docs.docker.com/config/containers/resource_constraints/
- You could split the mounts in RO (like genesis, config.toml) and RW (data, addressbook)

- Add liveness/ readyness checks with systemd ?
- Graceful shutdown is triggered by `docker stop` :+1:

see https://docs.docker.com/engine/reference/run/ , https://docs.docker.com/engine/reference/commandline/run/

**Comment by alpe** [comment]
@ruseinov have you launched a node with this setup as Dave has asked to confirm it?

**Comment by ruseinov** [comment]
> @ruseinov have you launched a node with this setup as Dave has asked to confirm it?

I have not, feeling a bit under today, so will poke at it on Monday to see if there are any issues. 
I have my concerns about running this in a container in general, but I guess for a sentry node it's np.

**Comment by davepuchyr** [comment]
> @alpe
> 
> > @ruseinov have you launched a node with this setup as Dave has asked to confirm it?
> 
> I have not, feeling a bit under today, so will poke at it on Monday to see if there are any issues.
> 
> I have my concerns about running this in a container in general, but I guess for a sentry node it's np.

OK, please let me know the best way to run a validator node.

**Comment by ruseinov** [comment]
Will do, basically it's via Go binaries directly. It would result in pretty much the same code you have now, minus the bits where you have to mount docker volumes. 

Gonna have to test it first. 
And it's also the way others are going to run this too.

**Comment by alpe** [comment]
As we don't create binaries as distribution artifacts, replacing docker would create a lot of additional work here. You would have to do the build steps on each machine or provide a distribution mechanism that includes verification of the artifact. 
If we plan to do this, it should be refined proper and a first class story. I had raised this several time in the past. This PR is about "systemd config"

**Comment by ruseinov** [comment]
> If we plan to do this, it should be refined proper and a first class story. I had raised this several time in the past. This PR is about "systemd config"

I think this is worth doing then. 
@davepuchyr If this could be added to our backlog - it'd be nice.

I think producing public docs that use docker for running a validator gives a wrong idea. @alpe WDYT? 

I will put it this way: if you think it is okay to run a validator in a container - I'm happy to test and merge this. If not - let's not do it and make the artifacts first. One of the reasons being that if these docs are used to run actual validators - we'll have to deal with docker-related problems and debug them + it's really not that good with performance in terms of disk io and consistency syncing to the host. 

I personally would prefer to avoid supporting docker-packaged validators unless we really need to, except for devnets or testnets that we own and control of course. 

All of the above is "IMHO" so I'm open to any suggestions.

**Comment by davepuchyr** [comment]
> > If we plan to do this, it should be refined proper and a first class story. I had raised this several time in the past. This PR is about "systemd config"
> 
> I think this is worth doing then.
> @davepuchyr If this could be added to our backlog - it'd be nice.

:)

I sent this at 8:01pm today via Slack (Martin's docs are unrelated to this issue):

Hi, Martin.  I haven't had a chance to go through your docs in detail yet because the validator program is gearing-up fast.  With regard to that, please make Alex's point in https://github.com/iov-one/docs/pull/21#issuecomment-510862136 the highest priority item for the upcoming sprint.

**Pull request merged**
